// Command gendocs writes the client compatibility page from the adapters
// themselves.
//
// Compatibility documentation written by hand goes stale within one release and
// then actively misleads, which for this page would be worse than having none:
// the whole product claim is that we tell people the truth about what each
// client will and will not take. Generating it from the adapters means the page
// cannot disagree with the code, and a test fails when it drifts.
//
// Run with `make docs`.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/agentbridgehq/agentbridge/internal/adapter"
	adapterreg "github.com/agentbridgehq/agentbridge/internal/adapter/registry"
	"github.com/agentbridgehq/agentbridge/internal/conformance"
	"gopkg.in/yaml.v3"
)

// clientResult renders one row of the conformance table by counting the
// results file, rather than by someone remembering to retype a number.
//
// The rows used to be hand-written while the agentbridge row was computed, and
// the hand-written ones went stale twice in a fortnight — both times for Codex,
// both times in the direction of the client having improved. A table that
// disagrees with the file it links to is worse than no table, because the link
// makes it look checked.
func clientResult(resultsDir, name, file string) string {
	raw, err := os.ReadFile(filepath.Join(resultsDir, file))
	if err != nil {
		return "| " + name + " | results unavailable |"
	}
	var doc struct {
		Version string `yaml:"version"`
		Results []struct {
			Outcome string `yaml:"outcome"`
		} `yaml:"results"`
	}
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		return "| " + name + " | results unreadable |"
	}
	counts := map[string]int{}
	for _, r := range doc.Results {
		counts[r.Outcome]++
	}
	var parts []string
	for _, k := range []string{"pass", "fail", "unmeasured"} {
		if counts[k] > 0 {
			parts = append(parts, fmt.Sprintf("%d %s", counts[k], k))
		}
	}
	version := doc.Version
	if version != "" {
		version = " (" + version + ")"
	}
	return fmt.Sprintf("| %s%s | %s — [results](../conformance/results/%s) |",
		name, version, strings.Join(parts, ", "), file)
}

// fence renders a fenced code block. Written as a helper because a raw string
// literal cannot contain the backticks a fence is made of.
func fence(lang string, lines ...string) string {
	return "```" + lang + "\n" + strings.Join(lines, "\n") + "\n```"
}

// selfConformance summarizes our own run, so the page cannot claim a result the
// corpus does not currently produce.
func selfConformance(corpus string) string {
	report, err := conformance.RunSelf(corpus)
	if err != nil {
		return "corpus unavailable"
	}
	return fmt.Sprintf("%d/%d cases pass", report.Count(conformance.Pass), len(report.Results))
}

func main() {
	out := Render("conformance/cases")
	if err := os.WriteFile("docs/clients.md", []byte(out), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gendocs: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("wrote docs/clients.md")

	index, err := conformance.Index("conformance/cases")
	if err != nil {
		fmt.Fprintf(os.Stderr, "gendocs: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile("conformance/index.json", index, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gendocs: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("wrote conformance/index.json")
}

// Render builds the page.
//
// The corpus path is a parameter rather than a constant so the freshness test
// can produce byte-identical output from its own directory. Resolving it
// relative to the caller made the generated page depend on where the generator
// ran from, which is exactly the kind of drift this file exists to prevent.
func Render(corpus string) string {
	// The results live beside the corpus, and both the generator and its test
	// call this with different relative roots. Deriving one from the other is
	// what keeps `make docs` and `go test ./internal/tools/gendocs` agreeing.
	resultsDir := filepath.Join(filepath.Dir(corpus), "results")
	var b strings.Builder

	b.WriteString(`# Client compatibility

<!--
Generated by internal/tools/gendocs from the adapters themselves. Run
` + "`make docs`" + ` after changing one. Do not edit by hand — a test compares this
file against the code and will fail.
-->

What each agent client actually takes, and what it does not.

**` + "`native`" + `** the client loads this as-is · **` + "`translated`" + `** we convert it into
the client's own format · **` + "`none`" + `** the client has no such concept ·
**` + "`undocumented`" + `** the client may well support it, but its vendor has not
published where the files go, and we will not write to a path we have not
verified.

| Client | Agent Plugins | Skills | MCP servers | Configuration |
|---|---|---|---|---|
`)

	// A zero Env is enough: this asks each adapter what it *is*, not what is
	// installed on the machine generating the page.
	adapters := adapterreg.Adapters(adapter.Env{})

	for _, a := range adapters {
		c := a.Client()
		conformant := "no"
		if c.Conformant {
			conformant = "yes"
		}
		fmt.Fprintf(&b, "| **%s** | %s | `%s` | `%s` | [docs](%s) |\n",
			c.Name, conformant, c.Skills, c.MCP, c.ConfigDoc)
	}

	b.WriteString(`
## The thing worth noticing

The one client that does **not** implement the standard carries the most, and
three that *do* carry the least. Claude Code is the only target whose plugin
layout its vendor documents, so it is the only one that receives skills at all.

That is not an accident of this implementation. **Conformance is not
documentation.** A client can implement Agent Plugins perfectly and still leave
nobody able to install a plugin into it programmatically, because where a
portable package goes on disk is a separate question that the specification
deliberately does not answer (§6.1 fixes locations *within* a plugin, not where
the plugin itself is installed).

Where a vendor has not published that location, the adapter declines to guess.
Writing into an unverified path on a developer's machine to make a table look
better is not a trade worth making, so those clients get their MCP servers and
an explicit note that their skills were not installed. Measuring the real
locations is what the conformance harness is for.

## What each client may not carry

Every loss below is reported at install time, with the reason. ` + "`by design`" + `
means the client genuinely cannot do it; ` + "`fault`" + ` means something went wrong and
can be fixed.

`)

	for _, a := range adapters {
		c := a.Client()
		fmt.Fprintf(&b, "### %s\n\n", c.Name)
		fmt.Fprintf(&b, "| Kind | Code | Meaning |\n|---|---|---|\n")

		for _, code := range c.Losses {
			info, ok := adapter.LookupLoss(code)
			if !ok {
				continue
			}
			kind := "fault"
			if info.Expected {
				kind = "by design"
			}
			fmt.Fprintf(&b, "| %s | `%s` | %s |\n", kind, info.Code, info.Meaning)
		}
		b.WriteString("\n")
	}

	b.WriteString(`## Adding a client

Adapters implement one interface and declare what they cannot carry. See
[` + "`internal/adapter`" + `](../internal/adapter) — an adapter may not emit a loss code
it has not declared, so a new failure mode has to be catalogued before it can
reach anyone.

## Declared, not measured

Everything above is **declared** by the adapters: it says what we write, based
on each vendor's own documentation. For most clients it does not say what they
then do with it, because nobody has watched.

Four have now been measured against the corpus, and the results are below. Codex
and opencode could be driven from their own CLIs — ` + "`codex debug prompt-input`" + `
and ` + "`opencode debug skill`" + ` report what was loaded, and with a source path for
each, so no model call is involved. Cursor and VS Code have no equivalent, so
those two were read back by a person asking the client what it had loaded.

That distinction is not pedantry. A conformant client may support neither
component type (§11.1), several requirements cannot be expressed in JSON Schema
so a schema-validating client accepts plugins the specification forbids, and in
one case following the published schema literally makes a client
*non-conformant*. Real compatibility is an empirical question.

The [conformance corpus](../conformance/README.md) is how it gets answered. It
is a set of plugin packages, each designed so a client's behaviour with it
answers one specific question, usable by anyone with no dependency on this tool:

` + fence("bash",
		"agentbridge conformance --list     # the corpus, as a manual checklist",
		"agentbridge conformance            # run it against this implementation") + `

| Target | Status |
|---|---|
| agentbridge | ` + selfConformance(corpus) + ` |
` + clientResult(resultsDir, "VS Code", "vscode.yaml") + `
` + clientResult(resultsDir, "Cursor", "cursor.yaml") + `
` + clientResult(resultsDir, "Codex", "codex.yaml") + `
` + clientResult(resultsDir, "Codex via the skills directory", "codex-skills-directory.yaml") + `
` + clientResult(resultsDir, "opencode", "opencode.yaml") + `
| Claude Code, Gemini CLI | not conformance targets; neither claims to implement the specification |

**Two clients load a conformant package, and the second one arrived while we
were writing this down.** Cursor accepted all 18 cases carrying only the
specification's plugin.json. Codex did not: up to and including 0.151.0 it
required .codex-plugin/plugin.json and rejected a conformant package with
"missing plugin.json". On 0.153.4 the same unmodified package installs and its
skills reach the model, measured against both versions. Claude Code still
requires .claude-plugin/; opencode and VS Code read no plugin manifest at all
and find skills by scanning directories. That is why most cases are unmeasured
rather than failed — a client that never reads the manifest is not failing to
validate it.

Two Codex findings went stale inside a fortnight, which is the argument for a
corpus anyone can re-run rather than a table we publish and defend.

Section 7.1 splits the field, and Codex splits down the middle by itself.
Skills must be immediate children of skills/, and a case ships one nested
deeper that must not be found. Cursor, VS Code and Codex-via-its-plugin-path
load only the two legitimate skills and pass. opencode loads all three and
fails, and so does Codex when the same package is dropped into its skills
directory instead: that scan is recursive where the plugin path scans one
level. One client, two answers, decided by how the bytes arrived rather than by
what they contain — which is worth raising upstream as a question about the
requirement, not only as bug reports.

Results are contributed as pull requests, and a case nobody ran is recorded as
` + "`unmeasured`" + ` rather than inferred. A blank row invites the reader to assume
something; a row saying nobody has checked does not.
`)

	return b.String()
}
