// Command gendocs writes the client compatibility page from the adapters
// themselves.
//
// Compatibility documentation written by hand goes stale within one release and
// then actively misleads, which for this page would be worse than having none:
// the whole product claim is that we tell people the truth about what each
// client will and will not take. Generating it from the adapters means the page
// cannot disagree with the code, and a test fails when it drifts.
//
// Run with `make docs`.
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/agentbridge/agentbridge/internal/adapter"
	adapterreg "github.com/agentbridge/agentbridge/internal/adapter/registry"
	"github.com/agentbridge/agentbridge/internal/conformance"
)

// fence renders a fenced code block. Written as a helper because a raw string
// literal cannot contain the backticks a fence is made of.
func fence(lang string, lines ...string) string {
	return "```" + lang + "\n" + strings.Join(lines, "\n") + "\n```"
}

// selfConformance summarizes our own run, so the page cannot claim a result the
// corpus does not currently produce.
func selfConformance(corpus string) string {
	report, err := conformance.RunSelf(corpus)
	if err != nil {
		return "corpus unavailable"
	}
	return fmt.Sprintf("%d/%d cases pass", report.Count(conformance.Pass), len(report.Results))
}

func main() {
	out := Render("conformance/cases")
	if err := os.WriteFile("docs/clients.md", []byte(out), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gendocs: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("wrote docs/clients.md")
}

// Render builds the page.
//
// The corpus path is a parameter rather than a constant so the freshness test
// can produce byte-identical output from its own directory. Resolving it
// relative to the caller made the generated page depend on where the generator
// ran from, which is exactly the kind of drift this file exists to prevent.
func Render(corpus string) string {
	var b strings.Builder

	b.WriteString(`# Client compatibility

<!--
Generated by internal/tools/gendocs from the adapters themselves. Run
` + "`make docs`" + ` after changing one. Do not edit by hand — a test compares this
file against the code and will fail.
-->

What each agent client actually takes, and what it does not.

**` + "`native`" + `** the client loads this as-is · **` + "`translated`" + `** we convert it into
the client's own format · **` + "`none`" + `** the client has no such concept ·
**` + "`undocumented`" + `** the client may well support it, but its vendor has not
published where the files go, and we will not write to a path we have not
verified.

| Client | Agent Plugins | Skills | MCP servers | Configuration |
|---|---|---|---|---|
`)

	// A zero Env is enough: this asks each adapter what it *is*, not what is
	// installed on the machine generating the page.
	adapters := adapterreg.Adapters(adapter.Env{})

	for _, a := range adapters {
		c := a.Client()
		conformant := "no"
		if c.Conformant {
			conformant = "yes"
		}
		fmt.Fprintf(&b, "| **%s** | %s | `%s` | `%s` | [docs](%s) |\n",
			c.Name, conformant, c.Skills, c.MCP, c.ConfigDoc)
	}

	b.WriteString(`
## The thing worth noticing

The one client that does **not** implement the standard carries the most, and
three that *do* carry the least. Claude Code is the only target whose plugin
layout its vendor documents, so it is the only one that receives skills at all.

That is not an accident of this implementation. **Conformance is not
documentation.** A client can implement Agent Plugins perfectly and still leave
nobody able to install a plugin into it programmatically, because where a
portable package goes on disk is a separate question that the specification
deliberately does not answer (§6.1 fixes locations *within* a plugin, not where
the plugin itself is installed).

Where a vendor has not published that location, the adapter declines to guess.
Writing into an unverified path on a developer's machine to make a table look
better is not a trade worth making, so those clients get their MCP servers and
an explicit note that their skills were not installed. Measuring the real
locations is what the conformance harness is for.

## What each client may not carry

Every loss below is reported at install time, with the reason. ` + "`by design`" + `
means the client genuinely cannot do it; ` + "`fault`" + ` means something went wrong and
can be fixed.

`)

	for _, a := range adapters {
		c := a.Client()
		fmt.Fprintf(&b, "### %s\n\n", c.Name)
		fmt.Fprintf(&b, "| Kind | Code | Meaning |\n|---|---|---|\n")

		for _, code := range c.Losses {
			info, ok := adapter.LookupLoss(code)
			if !ok {
				continue
			}
			kind := "fault"
			if info.Expected {
				kind = "by design"
			}
			fmt.Fprintf(&b, "| %s | `%s` | %s |\n", kind, info.Code, info.Meaning)
		}
		b.WriteString("\n")
	}

	b.WriteString(`## Adding a client

Adapters implement one interface and declare what they cannot carry. See
[` + "`internal/adapter`" + `](../internal/adapter) — an adapter may not emit a loss code
it has not declared, so a new failure mode has to be catalogued before it can
reach anyone.

## Declared, not measured

Everything above is **declared** by the adapters: it says what we write, based
on each vendor's own documentation. It does not say what the client then does
with it, because nobody has watched.

That distinction is not pedantry. A conformant client may support neither
component type (§11.1), several requirements cannot be expressed in JSON Schema
so a schema-validating client accepts plugins the specification forbids, and in
one case following the published schema literally makes a client
*non-conformant*. Real compatibility is an empirical question.

The [conformance corpus](../conformance/README.md) is how it gets answered. It
is a set of plugin packages, each designed so a client's behaviour with it
answers one specific question, usable by anyone with no dependency on this tool:

` + fence("bash",
		"agentbridge conformance --list     # the corpus, as a manual checklist",
		"agentbridge conformance            # run it against this implementation") + `

| Target | Status |
|---|---|
| agentbridge | ` + selfConformance(corpus) + ` |
| Claude Code, Cursor, VS Code, Codex, Gemini CLI | not yet measured |

Results are contributed as pull requests, and a case nobody ran is recorded as
` + "`unmeasured`" + ` rather than inferred. A blank row invites the reader to assume
something; a row saying nobody has checked does not.
`)

	return b.String()
}
